### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by SlowPixel** [Rinnegatamante/ff4a_vita#1]
At startup, a black screen, music goes on and you can hear the interface

tried versions .v.1.0.7 and .v.1.0.9

**Comment by Rinnegatamante** [comment]
Can't reproduce it even with a clean install.

**Comment by SlowPixel** [comment]
> Can't reproduce it even with a clean install.

Moreover, Final Fantasy 5 is working fine, is the version exactly the latest from Google Play?

**Comment by Rinnegatamante** [comment]
Yes

**Comment by SlowPixel** [comment]
[libff4a.zip](https://github.com/Rinnegatamante/ff4a_vita/files/9728441/libff4a.zip)

this one from version 1.0.6 came up
