### ISSUE TITLE
Please add Korean language support.

### ISSUE THREAD

**Issue by anabadah** [Rinnegatamante/ff4a_vita#5]
![캡처](https://github.com/Rinnegatamante/ff4a_vita/assets/117938813/34150b3a-2cd7-4cf5-a9ea-3bf4efc6e2a9)

Hi, the game is currently supported by Square Enix for the Korean language.

However, I can't select the Korean language because it's excluded from the ported game options.

If possible, could this be added in the next update?

Thanks.

**Comment by Rinnegatamante** [comment]
Done with v.1.0 release
